##############################################
#           Database Configuration           #
##############################################
spring:
  mvc:
    log-request-details: true
  datasource:
    url: jdbc:h2:mem:file:bankdb
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        show-sql: true

    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: create