
##############################################
#            Server Configuration            #
##############################################
server:
  port: 3000
  error:
    include-message: always
##############################################
#           Database Configuration           #
##############################################
logging:
  level:
    web: DEBUG #for additional information

springdoc:
  api-docs:
    path: /api-docs
    title: API Documentation
    description: API Documentation
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

spring:
  mvc:
    log-request-details: true
  datasource:
    url: jdbc:mysql://localhost:3306/library_db
    username: root
    password: q1w2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: create