
##############################################
#            Server Configuration            #
##############################################
server:
  port: 3000
  error:
    include-message: always

logging:
  level:
    web: DEBUG #for additional information

springdoc:
  api-docs:
    path: /api-docs
    title: API Documentation
    description: API Documentation
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

##############################################
#           Database Configuration           #
##############################################

spring:
  profiles:
    active: dev
